name: Step 0 – Check

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  check_ready_status:
    name: Advance to step 1
    needs: get_current_step

    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 0 }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Unlock markdown challenge
        id: check_ready
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          COMMENT: ${{ github.event.comment.body }}

        run: |
          COMMENT_LOWER=$(echo "$COMMENT" | tr '[:upper:]' '[:lower:]')
          if [[ "$COMMENT_LOWER" == "ready" ]]; then
            echo "✅ Learner is ready — advancing to Step 1"
            
            # Update issue body to Step 1 Markdown
            gh issue comment "${{ github.event.issue.number }}" \
              --body "✅ Learner is ready — advancing to Step 1"
            
            echo "ready=true" >> "$GITHUB_OUTPUT"
            git config user.name github-actions
            git config user.email github-actions@github.com
          else
            echo "❌ Comment does not match 'ready', ignoring"

            gh issue comment "${{ github.event.issue.number }}" \
              --body "❌ Comment does not match 'ready', ignoring"

            echo "ready=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

      - name: Update to step 1
        if: steps.check_ready.outputs.ready == 'true' #breaks with double quotes!
        uses: ./.github/actions/action-update-step-in-issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 0
          to_step: 1
          issue_number: ${{ github.event.issue.number }}
